Shay- introduction dded
bhklab/handbook pull request #84
Opened 2024-11-12 16:54 UTC by ShagReza

2024-11-26 17:02 UTC, mtran-code requested changes
This was really detailed and informative, thanks!

2024-11-26 17:02 UTC, mtran-code commented on docs/disciplines/Machine_Learning/index.md
> +   - Models are trained on labeled data (input-output pairs).
Fix the nested list formatting, the indented points need an extra space (4 spaces total)
```suggestion

    - Models are trained on labeled data (input-output pairs).
```

2024-11-26 17:02 UTC, mtran-code commented on docs/disciplines/Machine_Learning/index.md
> +   - Examples: Linear regression, support vector machines (SVMs).
```suggestion
    - Examples: Linear regression, support vector machines (SVMs).
```

2024-11-26 17:02 UTC, mtran-code commented on docs/disciplines/Machine_Learning/index.md
> +   - Models learn patterns from unlabeled data.
```suggestion

    - Models learn patterns from unlabeled data.
```

2024-11-26 17:02 UTC, mtran-code commented on docs/disciplines/Machine_Learning/index.md
> +   - Examples: Clustering (e.g., k-means), dimensionality reduction (e.g., PCA).
```suggestion
    - Examples: Clustering (e.g., k-means), dimensionality reduction (e.g., PCA).
```

2024-11-26 17:02 UTC, mtran-code commented on docs/disciplines/Machine_Learning/index.md
> +   - Models learn by interacting with an environment and receiving rewards or penalties.
```suggestion

    - Models learn by interacting with an environment and receiving rewards or penalties.
```

2024-11-26 17:02 UTC, mtran-code commented on docs/disciplines/Machine_Learning/index.md
> +   - Examples: Markov decision process (MDP), Deep Q Networks (DQN).
```suggestion
    - Examples: Markov decision process (MDP), Deep Q Networks (DQN).
```

2024-11-26 17:14 UTC, nabinelnino commented on docs/disciplines/Machine_Learning/index.md
> +   - Examples: Markov decision process (MDP), Deep Q Networks (DQN).
```suggestion
## Categories and Branches of Machine Learning

### Supervised Learning:

- Models are trained on labeled data (input-output pairs).
- Examples: Linear regression, support vector machines (SVMs).

### Unsupervised Learning:

- Models learn patterns from unlabeled data.
- Examples: Clustering (e.g., k-means), dimensionality reduction (e.g., PCA).

### Reinforcement Learning:

- Models learn by interacting with an environment and receiving rewards or penalties.
- Examples: Markov decision process (MDP), Deep Q Networks (DQN).
```suggestion
## Categories and Branches of Machine Learning

ML is broadly divided into three main categories:

1. **Supervised Learning**:
   - Models are trained on labeled data (input-output pairs).
   - Examples: Linear regression, support vector machines (SVMs).

2. **Unsupervised Learning**:
   - Models learn patterns from unlabeled data.
   - Examples: Clustering (e.g., k-means), dimensionality reduction (e.g., PCA).

3. **Reinforcement Learning**:
   - Models learn by interacting with an environment and receiving rewards or penalties.
   - Examples: Markov decision process (MDP), Deep Q Networks (DQN).
```

2024-11-27 21:41 UTC, mtran-code approved these changes

2024-11-29 20:32 UTC, merged