Added pages from med-imagenet to disciplines/Imaging
bhklab/handbook pull request #86
Opened 2024-11-12 16:55 UTC by JoshuaSiraj

Copied from: https://bhklab.github.io/med-imagenet/dev/Overview/

2024-11-26 16:22 UTC, fpvyas commented on docs/disciplines/Imaging/index.md
> +
don't forget to add the diagram

2024-11-26 16:23 UTC, fpvyas commented on docs/disciplines/Imaging/index.md
> +*add diagram showing a sample header with key metadata fields*
don't forget to add the diagram

2024-11-26 16:25 UTC, fpvyas commented on docs/disciplines/Imaging/index.md
> +\]
not sure if it's a markdown formatting issue, but it isn't clear what you're speaking about here or what this refers to

2024-11-26 16:27 UTC, fpvyas commented on docs/disciplines/Imaging/index.md
> +    \[
the markdown for this equation also doesn't show up properly

2024-11-26 16:28 UTC, fpvyas commented on docs/disciplines/Imaging/index.md
> +*add diagram comparing single file vs. two-file configurations*
don't forget the diagram

2024-11-26 16:30 UTC, fpvyas commented on docs/disciplines/Imaging/nifti.md
> +NIfTI structure diagram: <https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1diagrams_v2.pdf>
descriptor and link are not in the same line; if you could add a description to what this is supposed to show, would be useful

2024-11-26 16:33 UTC, fpvyas requested changes
very comprehensive and easy to understand! just needs some minor formatting fixes

2025-03-17 16:52 UTC, JoshuaSiraj reviewed
Looks good, just have one comment about the location of the nifti page

2025-03-17 16:52 UTC, JoshuaSiraj commented on docs/disciplines/Imaging/nifti.md
> -# Nifti Format
Should this not be under Data Types?

2025-03-17 18:54 UTC, merged