feat: Google Cloud Platform page added
bhklab/handbook pull request #92
Opened 2024-11-12 17:01 UTC by nabinelnino

2024-11-26 16:32 UTC, caryn-geady requested changes
looks great and very informative - just need to fix a few web links

2024-11-26 16:32 UTC, caryn-geady commented on docs/software_development/Remote_Development/Google_Cloud_Platform/index.md
> +- Visit the [Google Cloud Console](#https://console.cloud.google.com/) .
link doesn't work
```suggestion
- Visit the [Google Cloud Console](https://console.cloud.google.com/).
```

2024-11-26 16:32 UTC, caryn-geady commented on docs/software_development/Remote_Development/Google_Cloud_Platform/index.md
> +- Install the Google Cloud SDK on your machine by following the official installation guide (https://cloud.google.com/sdk/docs/install).
link
```suggestion
- Install the Google Cloud SDK on your machine by following the official [installation guide] (https://cloud.google.com/sdk/docs/install).
```

2024-11-26 16:32 UTC, caryn-geady commented on docs/software_development/Remote_Development/Google_Cloud_Platform/index.md
> +**Follow the instructions in this [document](#https://cloud.google.com/bigquery/docs) to learn more about BigQuery**
link
```suggestion
**Follow the instructions in this [document](https://cloud.google.com/bigquery/docs) to learn more about BigQuery**
```

2024-11-26 16:32 UTC, caryn-geady commented on docs/software_development/Remote_Development/Google_Cloud_Platform/index.md
> +Ensure that you have completed [How to Use GCP](#3-how-to-use-gcp) before starting this process.\_
```suggestion
Ensure that you have completed [How to Use GCP](#3-how-to-use-gcp) before starting this process.\
```

2024-11-26 16:32 UTC, caryn-geady commented on docs/software_development/Remote_Development/Google_Cloud_Platform/index.md
> +**For a detailed guide on using client services, please refer to this [link](#https://cloud.google.com/sql/docs)**
link
```suggestion
**For a detailed guide on using client services, please refer to this [link](https://cloud.google.com/sql/docs)**
```

2024-11-26 16:45 UTC, nabinelnino commented
fixed the suggested changes

2024-12-02 15:00 UTC, jjjermiah commented
is this good to go @nabinelnino @mtran-code ?

2024-12-02 15:02 UTC, mtran-code commented
I pushed the latest edits so maybe a review from anyone else first and then it's good.

2024-12-09 19:57 UTC, merged