feat: Adding a new page for STAR alignment
bhklab/handbook pull request #93
Opened 2024-11-12 17:18 UTC by PeterHHer

Created md file

2024-11-26 16:25 UTC, JoshuaSiraj commented on STAR.md
> +module load STAR/version_number
Make the use of version_number as a variable more explicit
```suggestion
module load STAR/<version_number>
# Replace <version_number> with the desired version, e.g., module load STAR/2.7.9a
```

2024-11-26 16:27 UTC, JoshuaSiraj commented on STAR.md
> +module load STAR/version_number
Make the use of version_number as a variable more explicit

```suggestion
module load STAR/<version_number>
# Replace <version_number> with the desired version, e.g., module load STAR/2.7.9a
```

2024-11-26 16:27 UTC, JoshuaSiraj commented on STAR.md
> +module load STAR/version_number
Make the use of version_number as a variable more explicit

```suggestion
# Replace <version_number> with the desired version, e.g., module load STAR/2.7.9a
```

2024-11-26 16:29 UTC, JoshuaSiraj commented on STAR.md
> +**`samples.txt`:**
Assuming there is supposed to be a file here?

2024-11-26 16:30 UTC, JoshuaSiraj commented on docs/disciplines/Bioinformatics/STAR.md
Move content from the other STAR.md to here

2024-11-26 16:30 UTC, JoshuaSiraj commented on STAR.md
Move content to docs/disciplines/Bioinformatics/STAR.md and delete

2024-11-26 16:31 UTC, JoshuaSiraj requested changes
Good work! Just need some changes

2024-12-02 15:01 UTC, jjjermiah commented
@PeterHHer can you please review these changes

2024-12-09 19:51 UTC, merged